[package]
name = "kunlun-pm"
description = "Independent Node-free Kunlun package-manager planning provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
base64.workspace = true
cap-std.workspace = true
libc.workspace = true
semver = "1.0.27"
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng = "0.10.0"
sha2.workspace = true

[lints]
workspace = true
